# Generated by Django 5.2.16 on 2026-08-04 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Directory name under PROBLEM_ROOT.', max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField(blank=True, help_text='HTML. Greek is fine.')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to students outside contests.')),
                ('time_limit', models.FloatField(default=1.0)),
                ('memory_limit_mb', models.IntegerField(default=256)),
                ('max_score', models.FloatField(default=100.0)),
                ('subtask_count', models.IntegerField(default=1)),
                ('test_count', models.IntegerField(default=0)),
                ('checker_type', models.CharField(default='token', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16)),
                ('source', models.TextField()),
                ('source_name', models.CharField(blank=True, help_text='Original filename, if uploaded.', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('judging', 'Judging'), ('done', 'Judged')], default='pending', max_length=16)),
                ('verdict', models.CharField(blank=True, max_length=8)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('cpu_time', models.FloatField(default=0.0)),
                ('memory_kb', models.IntegerField(default=0)),
                ('compile_output', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('feedback_mode', models.CharField(default='full', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('points', models.FloatField()),
                ('awarded', models.FloatField(default=0.0)),
                ('verdict', models.CharField(blank=True, max_length=8)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_results', to='core.submission')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('verdict', models.CharField(max_length=8)),
                ('score', models.FloatField(default=0.0)),
                ('cpu_time', models.FloatField(default=0.0)),
                ('memory_kb', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.submissionsubtask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='core_submis_status_7e9431_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='core_submis_user_id_f6fcc3_idx'),
        ),
    ]
