# Generated by Django 5.2.16 on 2026-08-04 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, help_text='HTML. Greek is fine.')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('scoring', models.CharField(choices=[('ioi', 'IOI — subtask points, ranked by total score'), ('icpc', 'ICPC — solved count, ranked by penalty time')], default='ioi', max_length=8)),
                ('penalty_minutes', models.IntegerField(default=20, help_text='ICPC only: penalty added per rejected attempt before an accepted one.')),
                ('freeze_minutes', models.IntegerField(default=0, help_text='Freeze the public scoreboard for the last N minutes. 0 disables freezing.')),
                ('feedback', models.CharField(choices=[('full', 'Full — every test shown'), ('subtask', 'Subtask scores only'), ('first', 'Verdict and first failing test'), ('minimal', 'Verdict only')], default='full', max_length=16)),
                ('reveal_after_end', models.BooleanField(default=True, help_text='Show full per-test detail once the contest is over.')),
                ('is_listed', models.BooleanField(default=False, help_text='Show on the contest list.')),
                ('open_registration', models.BooleanField(default=True, help_text='Students may register themselves.')),
                ('practice_after_end', models.BooleanField(default=True, help_text='Allow unranked submissions after the end time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A, B, C…', max_length=4)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Keep off the public scoreboard — testers, staff.')),
            ],
            options={
                'ordering': ['registered_at'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='counts_for_ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.contest'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest', 'created_at'], name='core_submis_contest_bee0fd_idx'),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='core.contest'),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contest_problems', to='core.problem'),
        ),
        migrations.AddField(
            model_name='participation',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.contest'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(fields=('contest', 'problem'), name='unique_problem_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(fields=('contest', 'label'), name='unique_label_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='unique_participation'),
        ),
    ]
