# Generated by Django 5.2.16 on 2026-08-12 08:49

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contest_contestproblem_participation_and_more'),
    ]

def copy_statements_forward(apps, schema_editor):
    """Move any existing Problem.statement HTML into a Statement row.

    Without this the upgrade silently discards statements that were already
    written. They were HTML, so they keep body_format='html'; Greek is the
    default language here because that is what these were written in.
    """
    Problem = apps.get_model('core', 'Problem')
    Statement = apps.get_model('core', 'Statement')
    for problem in Problem.objects.exclude(statement='').exclude(statement=None):
        Statement.objects.create(
            problem=problem, language='el', body_format='html',
            body=problem.statement, is_default=True,
        )


def copy_statements_backward(apps, schema_editor):
    Problem = apps.get_model('core', 'Problem')
    Statement = apps.get_model('core', 'Statement')
    for statement in Statement.objects.filter(is_default=True):
        Problem.objects.filter(pk=statement.problem_id).update(statement=statement.body)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contest_contestproblem_participation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('el', 'Ελληνικά'), ('en', 'English')], default='el', max_length=5)),
                ('title', models.CharField(blank=True, help_text='Problem title in this language. Falls back to the problem title.', max_length=200)),
                ('body_format', models.CharField(choices=[('md', 'Markdown'), ('html', 'HTML')], default='md', max_length=8)),
                ('body', models.TextField(blank=True, help_text='Maths: $inline$ and $$display$$.')),
                ('pdf', models.FileField(blank=True, help_text='Optional. Shown alongside the text, or alone if there is no text.', null=True, upload_to=core.models.statement_upload_path)),
                ('is_default', models.BooleanField(default=False, help_text='Shown first when the reader has no preference.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='core.problem')),
            ],
            options={
                'ordering': ['-is_default', 'language'],
                'constraints': [models.UniqueConstraint(fields=('problem', 'language'), name='unique_statement_language')],
            },
        ),
    ]
    operations += [
        migrations.RunPython(copy_statements_forward, copy_statements_backward),
        migrations.RemoveField(
            model_name='problem',
            name='statement',
        ),
    ]
